Repository Pharmanathi/pharmanathi.com, pull requests merged in 2025-02, with the labels that each got.

#441 fix: removing one Working Hour row removes two
  mobile_mhp/lib/views/widgets/WorkingHoursInput.dart
Labels: bug, MHP

#439 ci(backend): add step for creating env file
  .github/workflows/backend.yml
Labels: build, ci, python

#438 Fix issue 434
  mobile_mhp/lib/views/screens/sign_in.dart
  mobile_mhp/lib/views/widgets/WorkingHoursInput.dart
  pharmanathi.com/.envs/.local/example.postgres
  pharmanathi.com/.envs/.local/example.verifi
Labels: MHP-&-Patient, bug, MHP

#440 fix:sorting Working Hours in ascending order
  mobile_mhp/lib/views/widgets/upcoming_appointment_tile.dart
  mobile_patient/lib/views/screens/doctors.dart
  mobile_patient/lib/views/widgets/appointment_details_tile.dart
  mobile_patient/lib/views/widgets/calender.dart
Labels: bug, refactor

#450 Implement FCM client
  .github/workflows/backend.yml
  mobile_mhp/android/app/src/main/AndroidManifest.xml
  mobile_mhp/lib/services/api_provider.dart
  mobile_patient/android/app/src/main/AndroidManifest.xml
  mobile_patient/lib/services/api_provider.dart
  pharmanathi.com/.gitignore
  pharmanathi.com/config/settings/base.py
  pharmanathi.com/config/settings/local.py
  pharmanathi.com/config/settings/production.py
  pharmanathi.com/pharmanathi_backend/appointments/migrations/0003_alter_timeslot_options.py
  pharmanathi.com/pharmanathi_backend/appointments/models.py
  pharmanathi.com/pharmanathi_backend/users/admin.py
  pharmanathi.com/pharmanathi_backend/users/api/views.py
  pharmanathi.com/pharmanathi_backend/users/migrations/0002_user_device_token.py
  pharmanathi.com/pharmanathi_backend/users/models.py
  pharmanathi.com/pharmanathi_backend/users/tasks.py
  pharmanathi.com/pharmanathi_backend/utils/fcm_client.py
  pharmanathi.com/requirements/django/base.txt
  pharmanathi.com/requirements/django/production.txt
  pharmanathi.com/service-account.json.example
Labels: chore, feat, build
